name: gen_newspaper

on:
  schedule:
    - cron: '30 22 * * *'
  workflow_dispatch:

jobs:
  gen_newspaper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - run: uv run python -m bignews.generate_newspaper
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_BASE_URL: ${{ secrets.OPENAI_BASE_URL }}
